/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carlosrivera_lab6;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Usuario Dell
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.Arbol.setModal(true);
        this.Arbol.pack();
        this.Arbol.setLocationRelativeTo(this);
        this.Arbol.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Arbol = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbol_general = new javax.swing.JTree();
        Agregar_Persona = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombre_empleado = new javax.swing.JTextField();
        id_empleado = new javax.swing.JTextField();
        nacionalidad_empleado = new javax.swing.JComboBox<>();
        lugar_empleado = new javax.swing.JTextField();
        bt_color_empleado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        bt_agregar_empleado = new javax.swing.JButton();
        edad_empleado = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        entrada_empleado = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        salida_empleado = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        sueldo_empleado = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        estado_empleado = new javax.swing.JComboBox<>();
        seccion_empleado = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nombre_cliente = new javax.swing.JTextField();
        id_cliente = new javax.swing.JTextField();
        nacionalidad_cliente = new javax.swing.JComboBox<>();
        lugar_cliente = new javax.swing.JTextField();
        bt_color_cliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        agregar_cliente = new javax.swing.JButton();
        edad_cliente = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        ticket_cliente = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        dinero_cliente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nombre_jefe = new javax.swing.JTextField();
        id_jefe = new javax.swing.JTextField();
        nacionalidad_jefe = new javax.swing.JComboBox<>();
        lugar_jefe = new javax.swing.JTextField();
        bt_color_jefe = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        arbol_empleado = new javax.swing.JTree();
        bt_agregar_jefe = new javax.swing.JButton();
        edad_jefe = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cliente_jefe = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        ganancias_jefe = new javax.swing.JTextField();
        seccion_jefe = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        agregar_familiares = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        nombre_familiar = new javax.swing.JTextField();
        edad_familiar = new javax.swing.JSpinner();
        id_familiar = new javax.swing.JTextField();
        nacionalidad_familiar = new javax.swing.JComboBox<>();
        lugar_familiar = new javax.swing.JTextField();
        bt_color_familiar = new javax.swing.JButton();
        agregar_familiar = new javax.swing.JButton();
        menu_popup = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        eliminar = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla_general = new javax.swing.JTable();
        menu_popup2 = new javax.swing.JPopupMenu();
        eliminar_tabla = new javax.swing.JMenuItem();
        ordenes = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        cb_baleadas = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        precio_baleadas = new javax.swing.JTextField();
        agregar_baleadas = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        cb_empleados = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        precio_gato = new javax.swing.JTextField();
        altura_gato = new javax.swing.JTextField();
        peso_gato = new javax.swing.JTextField();
        agregar_gato = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        guardar_empleado = new javax.swing.JMenuItem();
        guardar_cliente = new javax.swing.JMenuItem();
        guardar_jefes = new javax.swing.JMenuItem();
        guardar_familiares = new javax.swing.JMenuItem();
        guardar_gatos = new javax.swing.JMenuItem();
        guardar_baleadas = new javax.swing.JMenuItem();
        guardar_ordenes = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Raiz");
        arbol_general.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbol_general.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbol_generalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(arbol_general);

        javax.swing.GroupLayout ArbolLayout = new javax.swing.GroupLayout(Arbol.getContentPane());
        Arbol.getContentPane().setLayout(ArbolLayout);
        ArbolLayout.setHorizontalGroup(
            ArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArbolLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        ArbolLayout.setVerticalGroup(
            ArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArbolLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jLabel1.setText("Nombre");

        jLabel2.setText("Id");

        jLabel3.setText("Edad");

        jLabel4.setText("Nacionalidad");

        jLabel5.setText("Lugar Nacimiento");

        jLabel6.setText("Color de Piel");

        jLabel7.setText("Arbol Genealogico");

        nacionalidad_empleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hondureño", "Estado Unidense", "Mexicano", "Italiano", "Gautemalteco" }));

        bt_color_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_color_empleadoActionPerformed(evt);
            }
        });

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Raiz");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jTree1);

        bt_agregar_empleado.setText("Agregar");
        bt_agregar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregar_empleadoActionPerformed(evt);
            }
        });

        jLabel29.setText("Seccion Trabajada");

        jLabel30.setText("Horas de Entrada");

        jLabel31.setText("Hora de Salida");

        jLabel32.setText("Sueldo");

        jLabel33.setText("Estado");

        estado_empleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ocupado", "Disponible" }));

        seccion_empleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cocina", "Venta de Gatos", "Venta de Baleadas" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nacionalidad_empleado, 0, 144, Short.MAX_VALUE)
                    .addComponent(lugar_empleado)
                    .addComponent(bt_color_empleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(id_empleado)
                    .addComponent(edad_empleado)
                    .addComponent(nombre_empleado))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(bt_agregar_empleado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(entrada_empleado)
                            .addComponent(salida_empleado)
                            .addComponent(sueldo_empleado)
                            .addComponent(estado_empleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seccion_empleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(seccion_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(entrada_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edad_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(salida_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nacionalidad_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(sueldo_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lugar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel33)
                        .addComponent(estado_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(bt_color_empleado, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(bt_agregar_empleado)
                        .addGap(119, 119, 119))))
        );

        jTabbedPane1.addTab("Empleado", jPanel1);

        jLabel8.setText("Nombre");

        jLabel9.setText("Id");

        jLabel10.setText("Edad");

        jLabel11.setText("Nacionalidad");

        jLabel12.setText("Lugar Nacimiento");

        jLabel13.setText("Color de Piel");

        jLabel14.setText("Arbol Genealogico");

        nacionalidad_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hondureño", "Estado Unidense", "Mexicano", "Italiano", "Gautemalteco" }));

        bt_color_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_color_clienteActionPerformed(evt);
            }
        });

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Raiz");
        jTree2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jTree2);

        agregar_cliente.setText("Agregar");
        agregar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_clienteActionPerformed(evt);
            }
        });

        jLabel34.setText("Numero de Ticket");

        jLabel35.setText("Dinero");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_color_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(id_cliente)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edad_cliente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nacionalidad_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lugar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregar_cliente)
                        .addGap(94, 94, 94))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ticket_cliente)
                            .addComponent(dinero_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(ticket_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(dinero_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(edad_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nacionalidad_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lugar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(bt_color_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregar_cliente)
                        .addGap(104, 104, 104))))
        );

        jTabbedPane1.addTab("Cliente", jPanel2);

        jLabel15.setText("Nombre");

        jLabel16.setText("Id");

        jLabel17.setText("Edad");

        jLabel18.setText("Nacionalidad");

        jLabel19.setText("Lugar Nacimiento");

        jLabel20.setText("Color de Piel");

        jLabel21.setText("Arbol Genealogico");

        nacionalidad_jefe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hondureño", "Estado Unidense", "Mexicano", "Italiano", "Gautemalteco" }));

        bt_color_jefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_color_jefeActionPerformed(evt);
            }
        });

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Raiz");
        arbol_empleado.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane4.setViewportView(arbol_empleado);

        bt_agregar_jefe.setText("Agregar");
        bt_agregar_jefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregar_jefeActionPerformed(evt);
            }
        });

        jLabel36.setText("Seccion Trabajada");

        jLabel37.setText("Clientes Atendidos");

        jLabel38.setText("Ganancias");

        seccion_jefe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Venta de Gatos", "Venta de Baleadas" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nombre_jefe))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(id_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nacionalidad_jefe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lugar_jefe))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_color_jefe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edad_jefe)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(bt_agregar_jefe)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cliente_jefe)
                            .addComponent(ganancias_jefe)
                            .addComponent(seccion_jefe, 0, 158, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(nombre_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(seccion_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(id_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(cliente_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(edad_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(ganancias_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(nacionalidad_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lugar_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(bt_color_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(bt_agregar_jefe)
                        .addGap(132, 132, 132))))
        );

        jTabbedPane1.addTab("Jefes", jPanel3);

        javax.swing.GroupLayout Agregar_PersonaLayout = new javax.swing.GroupLayout(Agregar_Persona.getContentPane());
        Agregar_Persona.getContentPane().setLayout(Agregar_PersonaLayout);
        Agregar_PersonaLayout.setHorizontalGroup(
            Agregar_PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_PersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        Agregar_PersonaLayout.setVerticalGroup(
            Agregar_PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_PersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jLabel22.setText("Nombre");

        jLabel24.setText("Edad");

        jLabel25.setText("Id");

        jLabel26.setText("Nacionalidad");

        jLabel27.setText("Lugar de Nacimiento");

        jLabel28.setText("Color de Piel");

        nacionalidad_familiar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hondureño", "Mexicano", "Estado Unidense", "Italiano" }));

        bt_color_familiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_color_familiarActionPerformed(evt);
            }
        });

        agregar_familiar.setText("Agregar");
        agregar_familiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_familiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout agregar_familiaresLayout = new javax.swing.GroupLayout(agregar_familiares.getContentPane());
        agregar_familiares.getContentPane().setLayout(agregar_familiaresLayout);
        agregar_familiaresLayout.setHorizontalGroup(
            agregar_familiaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregar_familiaresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(8, 8, 8)
                .addGroup(agregar_familiaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(agregar_familiaresLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(agregar_familiaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edad_familiar)
                    .addComponent(id_familiar)
                    .addComponent(nombre_familiar)
                    .addComponent(nacionalidad_familiar, 0, 150, Short.MAX_VALUE)
                    .addComponent(lugar_familiar)
                    .addComponent(bt_color_familiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(125, 125, 125))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregar_familiaresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregar_familiar)
                .addGap(180, 180, 180))
        );
        agregar_familiaresLayout.setVerticalGroup(
            agregar_familiaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregar_familiaresLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(agregar_familiaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(nombre_familiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(agregar_familiaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregar_familiaresLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addGroup(agregar_familiaresLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(edad_familiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(agregar_familiaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_familiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agregar_familiaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nacionalidad_familiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(agregar_familiaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lugar_familiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(agregar_familiaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(bt_color_familiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(agregar_familiar)
                .addGap(35, 35, 35))
        );

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        menu_popup.add(Modificar);

        tabla_general.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Id", "Nacionalidad"
            }
        ));
        tabla_general.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_generalMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabla_general);

        javax.swing.GroupLayout eliminarLayout = new javax.swing.GroupLayout(eliminar.getContentPane());
        eliminar.getContentPane().setLayout(eliminarLayout);
        eliminarLayout.setHorizontalGroup(
            eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );
        eliminarLayout.setVerticalGroup(
            eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        eliminar_tabla.setText("jMenuItem1");
        eliminar_tabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_tablaActionPerformed(evt);
            }
        });
        menu_popup2.add(eliminar_tabla);

        jLabel42.setText("Precio");

        agregar_baleadas.setText("Agregar");
        agregar_baleadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_baleadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addGap(81, 81, 81)
                                .addComponent(precio_baleadas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb_baleadas, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(agregar_baleadas)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(cb_baleadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(precio_baleadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(agregar_baleadas)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Baleadas", jPanel5);

        jLabel39.setText("Precio");

        jLabel40.setText("Altura");

        jLabel41.setText("Peso");

        agregar_gato.setText("Agregar");
        agregar_gato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_gatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel41))
                                .addGap(103, 103, 103)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(precio_gato)
                                    .addComponent(altura_gato)
                                    .addComponent(peso_gato, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(agregar_gato)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cb_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(precio_gato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(altura_gato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(peso_gato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(agregar_gato)
                .addGap(29, 29, 29))
        );

        jTabbedPane2.addTab("Gatos", jPanel4);

        javax.swing.GroupLayout ordenesLayout = new javax.swing.GroupLayout(ordenes.getContentPane());
        ordenes.getContentPane().setLayout(ordenesLayout);
        ordenesLayout.setHorizontalGroup(
            ordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        ordenesLayout.setVerticalGroup(
            ordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Agregar Persona");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton8.setText("Agregar Familiar");

        jButton9.setText("Ventas");

        jButton10.setText("Ordenes");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Reporte de Ganancias");

        jButton12.setText("Abrir Arbol");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("Opciones");

        jMenu2.setText("Guardar");

        guardar_empleado.setText("Guardar Empleados");
        guardar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_empleadoActionPerformed(evt);
            }
        });
        jMenu2.add(guardar_empleado);

        guardar_cliente.setText("Guardar Clientes");
        guardar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_clienteActionPerformed(evt);
            }
        });
        jMenu2.add(guardar_cliente);

        guardar_jefes.setText("Guardar Jefes");
        guardar_jefes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_jefesActionPerformed(evt);
            }
        });
        jMenu2.add(guardar_jefes);

        guardar_familiares.setText("Guardar Familiares");
        guardar_familiares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_familiaresActionPerformed(evt);
            }
        });
        jMenu2.add(guardar_familiares);

        guardar_gatos.setText("Guardar Gatos");
        guardar_gatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_gatosActionPerformed(evt);
            }
        });
        jMenu2.add(guardar_gatos);

        guardar_baleadas.setText("Guardar Baleadas");
        guardar_baleadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_baleadasActionPerformed(evt);
            }
        });
        jMenu2.add(guardar_baleadas);

        guardar_ordenes.setText("Guardar Ordenes");
        guardar_ordenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_ordenesActionPerformed(evt);
            }
        });
        jMenu2.add(guardar_ordenes);

        jMenu1.add(jMenu2);

        jMenuItem2.setText("Guardar Como");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("About");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(96, 96, 96)
                        .addComponent(jButton10))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(61, 61, 61)
                            .addComponent(jButton12)))
                    .addComponent(jButton11))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton12))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton8)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.Agregar_Persona.setModal(true);
        this.Agregar_Persona.pack();
        this.Agregar_Persona.setLocationRelativeTo(this);
        this.Agregar_Persona.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        this.Arbol.setModal(true);
        this.Arbol.pack();
        this.Arbol.setLocationRelativeTo(this);
        this.Arbol.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void bt_agregar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregar_empleadoActionPerformed
        // TODO add your handling code here:
        try {
            nombre = nombre_empleado.getText();
            edad = (Integer) edad_empleado.getValue();
            id = Integer.parseInt(id_empleado.getText());
            nacionalidad = (String) nacionalidad_empleado.getSelectedItem();
            lugar_nacimiento = lugar_empleado.getText();
            color_piel = bt_color_empleado.getBackground();
            seccion_trabajo = (String) seccion_empleado.getSelectedItem();
            hora_entrado = entrada_empleado.getText();
            hora_salida = salida_empleado.getText();
            estado = (String) estado_empleado.getSelectedItem();
            sueldo = Double.parseDouble(sueldo_empleado.getText());
            lista.add(new Empleado(seccion_trabajo, hora_entrado, hora_salida,
                    sueldo, estado, edad, id, nacionalidad, lugar_nacimiento,
                    nombre, color_piel, null));
            JOptionPane.showMessageDialog(this, "El empleado fue agregado");
            DefaultTreeModel m = (DefaultTreeModel) arbol_general.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            DefaultMutableTreeNode nodo_persona;
            nodo_persona = new DefaultMutableTreeNode(new Empleado(
                    seccion_trabajo, hora_entrado, hora_salida, sueldo, estado,
                    edad, id, nacionalidad, lugar_nacimiento, nombre, color_piel, null));
            raiz.add(nodo_persona);
            m.reload();

            DefaultTableModel modelo = (DefaultTableModel) tabla_general.getModel();
            Object[] newrow = {nombre_empleado.getText(), edad_empleado.getValue(), id_empleado.getText(), nacionalidad_empleado.getSelectedItem()};
            modelo.addRow(newrow);
            tabla_general.setModel(modelo);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_bt_agregar_empleadoActionPerformed

    private void bt_color_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_color_empleadoActionPerformed
        // TODO add your handling code here:
        bt_color_empleado.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));
    }//GEN-LAST:event_bt_color_empleadoActionPerformed

    private void agregar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_clienteActionPerformed
        // TODO add your handling code here:
        try {
            nombre = nombre_cliente.getText();
            edad = (Integer) edad_cliente.getValue();
            id = Integer.parseInt(id_cliente.getText());
            nacionalidad = (String) nacionalidad_cliente.getSelectedItem();
            lugar_nacimiento = lugar_cliente.getText();
            color_piel = bt_color_cliente.getBackground();
            ticket = Integer.parseInt(ticket_cliente.getText());
            dinero = Double.parseDouble(dinero_cliente.getText());
            lista.add(new Cliente(ticket, dinero, edad, id, nacionalidad,
                    lugar_nacimiento, nombre, color_piel, null));
            JOptionPane.showMessageDialog(this, "El cliente fue agregado");
            DefaultTreeModel m = (DefaultTreeModel) arbol_general.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            DefaultMutableTreeNode nodo_persona;
            nodo_persona = new DefaultMutableTreeNode(new Cliente(
                    ticket, dinero, edad, id, nacionalidad,
                    lugar_nacimiento, nombre, color_piel, null));
            raiz.add(nodo_persona);
            m.reload();

            DefaultTableModel modelo = (DefaultTableModel) tabla_general.getModel();
            Object[] newrow = {nombre_cliente.getText(), edad_cliente.getValue(), id_cliente.getText(), nacionalidad_cliente.getSelectedItem()};
            modelo.addRow(newrow);
            tabla_general.setModel(modelo);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_agregar_clienteActionPerformed

    private void bt_color_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_color_clienteActionPerformed
        // TODO add your handling code here:  
        bt_color_cliente.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));
    }//GEN-LAST:event_bt_color_clienteActionPerformed

    private void bt_color_jefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_color_jefeActionPerformed
        // TODO add your handling code here:
        bt_color_jefe.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));

    }//GEN-LAST:event_bt_color_jefeActionPerformed

    private void bt_agregar_jefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregar_jefeActionPerformed
        // TODO add your handling code here:
        try {
            nombre = nombre_jefe.getText();
            edad = (Integer) edad_jefe.getValue();
            id = Integer.parseInt(id_jefe.getText());
            nacionalidad = (String) nacionalidad_cliente.getSelectedItem();
            lugar_nacimiento = lugar_cliente.getText();
            color_piel = bt_color_cliente.getBackground();
            seccion_trabajo = (String) seccion_jefe.getSelectedItem();
            clientes_atendidos = Integer.parseInt(cliente_jefe.getText());
            ganacias = Double.parseDouble(ganancias_jefe.getText());
            lista.add(new Jefes(seccion_trabajo, clientes_atendidos, ganacias,
                    edad, id, nacionalidad, lugar_nacimiento, nombre, color_piel, null));
            JOptionPane.showMessageDialog(this, "El jefe fue agregado ");
            DefaultTreeModel m = (DefaultTreeModel) arbol_general.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            DefaultMutableTreeNode nodo_persona;
            nodo_persona = new DefaultMutableTreeNode(new Jefes(seccion_trabajo,
                    clientes_atendidos, ganacias, edad, id, nacionalidad,
                    lugar_nacimiento, nombre, color_piel, null));
            raiz.add(nodo_persona);
            m.reload();

            DefaultTableModel modelo = (DefaultTableModel) tabla_general.getModel();
            Object[] newrow = {nombre_jefe.getText(), edad_empleado.getValue(), id_empleado.getText(), nacionalidad_empleado.getSelectedItem()};
            modelo.addRow(newrow);
            tabla_general.setModel(modelo);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_bt_agregar_jefeActionPerformed

    private void guardar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_empleadoActionPerformed
        // TODO add your handling code here:
        AdminEmpleado ae = new AdminEmpleado("./empleados.txt");
        if (ae.getArchivo().exists()) {
            ae.cargarArchivo();
            ae.setEmpleado(new Empleado(seccion_trabajo, hora_entrado,
                    hora_salida, sueldo, estado, edad, id, nacionalidad,
                    lugar_nacimiento, nombre, color_piel, null));
        }
        ae.escribirArchivo();

    }//GEN-LAST:event_guardar_empleadoActionPerformed

    private void guardar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_clienteActionPerformed
        // TODO add your handling code here:
        AdminClientes ac = new AdminClientes("./clientes.txt");
        if (ac.getArchivo().exists()) {
            ac.cargarArchivo();
            ac.setClientes(new Cliente(ticket, dinero, edad, id,
                    nacionalidad, lugar_nacimiento, nombre, color_piel, null));
        }
        ac.escribirArchivo();
    }//GEN-LAST:event_guardar_clienteActionPerformed

    private void guardar_jefesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_jefesActionPerformed
        // TODO add your handling code here:
        AdminJefe aj = new AdminJefe("./jefe.txt");
        if (aj.getArchivo().exists()) {
            aj.getArchivo();
            aj.setJefes(new Jefes(seccion_trabajo, clientes_atendidos, ganacias, edad, id, nacionalidad, lugar_nacimiento, nombre, color_piel, null));
        }
        aj.escribirArchivo();
    }//GEN-LAST:event_guardar_jefesActionPerformed

    private void guardar_familiaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_familiaresActionPerformed
        // TODO add your handling code here:
        AdminFamiliar af = new AdminFamiliar("./familiares.txt");
        if (af.getArchivo().exists()) {
            af.getArchivo();
            af.setFamiliares(new Familiares(edad, id, nacionalidad, lugar_nacimiento, nombre, color_piel, new Familiares()));
        }
        af.escribriArchivo();
    }//GEN-LAST:event_guardar_familiaresActionPerformed

    private void guardar_gatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_gatosActionPerformed
        // TODO add your handling code here:
        AdminGatos ag = new AdminGatos("./gatos.txt");
        if (ag.getArchivo().exists()) {
            ag.cargarArchivo();
            ag.setGato(new Gato(peso, altura, precio));
        }
        ag.escribirArchivo();
    }//GEN-LAST:event_guardar_gatosActionPerformed

    private void guardar_baleadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_baleadasActionPerformed
        // TODO add your handling code here:
        AdminBaleadas ab = new AdminBaleadas("./baleadas.txt");
        if (ab.getArchivo().exists()) {
            ab.cargarArchivo();
            ab.setBaleada(new Baleadas(precio));
        }
        ab.escribirArchivo();
    }//GEN-LAST:event_guardar_baleadasActionPerformed

    private void guardar_ordenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_ordenesActionPerformed
        // TODO add your handling code here:
        AdminOrdenes ao = new AdminOrdenes("./ordenes.txt");

        if (ao.getArchivo().exists()) {
            ao.cargarArchivo();
        }
        ao.escribirArchivo();
    }//GEN-LAST:event_guardar_ordenesActionPerformed

    private void arbol_generalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbol_generalMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = arbol_general.getClosestRowForLocation(evt.getX(), evt.getY());
            arbol_general.setSelectionRow(row);
            Object v1 = arbol_general.getSelectionPath().getLastPathComponent();
            nodo_selecionado = (DefaultMutableTreeNode) v1;
            if (nodo_selecionado.getUserObject() instanceof Persona) {
                persona_seleccionado = (Persona) nodo_selecionado.getUserObject();
                menu_popup.show(evt.getComponent(), evt.getX(), evt.getY());

            }
        }

    }//GEN-LAST:event_arbol_generalMouseClicked

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        nombre = JOptionPane.showInputDialog("Ingrese el nombre ");
        persona_seleccionado.setNombre(nombre);
//        familiar_seleccionado.setNombre(nombre);
        edad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la edad "));
        persona_seleccionado.setEdad(edad);
        //  familiar_seleccionado.setEdad(edad);
        id = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la id "));
        persona_seleccionado.getId();

        //   familiar_seleccionado.getId();
    }//GEN-LAST:event_ModificarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.eliminar.setModal(true);
        this.eliminar.pack();
        this.eliminar.setLocationRelativeTo(this);
        this.eliminar.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabla_generalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_generalMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int pp = tabla_general.getSelectedRow();
            menu_popup2.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tabla_generalMouseClicked

    private void eliminar_tablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_tablaActionPerformed
        // TODO add your handling code here:
        if (tabla_general.getSelectedRow() >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) tabla_general.getModel();
            lista.remove(tabla_general.getSelectedRow());
            tabla_general.setModel(modelo);
        }
    }//GEN-LAST:event_eliminar_tablaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        int seleccion = jfc.showSaveDialog(this);
        FileWriter fw = null;
        BufferedWriter bw = null;
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                File fichero = jfc.getSelectedFile();
                fw = new FileWriter(fichero);
                bw = new BufferedWriter(fw);

                bw.flush();
                JOptionPane.showMessageDialog(this, "Archivo creado ");
            } catch (Exception e) {
            } finally {
                try {
                    bw.close();
                    fw.close();
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        this.ordenes.setModal(true);
        this.ordenes.pack();
        this.ordenes.setLocationRelativeTo(this);
        this.ordenes.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void agregar_gatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_gatoActionPerformed
        // TODO add your handling code here:
        try {
            precio = Double.parseDouble(precio_gato.getText());
            peso = Double.parseDouble(peso_gato.getText());
            altura = Double.parseDouble(altura_gato.getText());
            lista.add(new Gato(peso, altura, precio));
        } catch (Exception e) {
        }


    }//GEN-LAST:event_agregar_gatoActionPerformed

    private void agregar_baleadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_baleadasActionPerformed
        // TODO add your handling code here:
        try {
            precio = Double.parseDouble(precio_baleadas.getText());
            lista.add(new Baleadas(precio));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_agregar_baleadasActionPerformed

    private void agregar_familiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_familiarActionPerformed
        // TODO add your handling code here:
        try {
            nombre = nombre_familiar.getText();
            edad = (Integer) edad_familiar.getValue();
            id = Integer.parseInt(id_familiar.getText());
            nacionalidad = (String) nacionalidad_familiar.getSelectedItem();
            lugar_nacimiento = lugar_familiar.getText();
            color_piel = bt_color_familiar.getBackground();
            lista.add(new Familiares(edad, id, nacionalidad, lugar_nacimiento, nombre, color_piel, new Familiares()));

            JOptionPane.showMessageDialog(this, "El familiar fue agregado ");
            DefaultTreeModel m = (DefaultTreeModel) arbol_general.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            DefaultMutableTreeNode nodo_persona;
            nodo_persona = new DefaultMutableTreeNode(new Familiares(edad, id,
                    nacionalidad, lugar_nacimiento, nombre, color_piel, new Familiares()));
            raiz.add(nodo_persona);
            m.reload();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_agregar_familiarActionPerformed

    private void bt_color_familiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_color_familiarActionPerformed
        // TODO add your handling code here:    
        bt_color_familiar.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));

    }//GEN-LAST:event_bt_color_familiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Agregar_Persona;
    private javax.swing.JDialog Arbol;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JButton agregar_baleadas;
    private javax.swing.JButton agregar_cliente;
    private javax.swing.JButton agregar_familiar;
    private javax.swing.JDialog agregar_familiares;
    private javax.swing.JButton agregar_gato;
    private javax.swing.JTextField altura_gato;
    private javax.swing.JTree arbol_empleado;
    private javax.swing.JTree arbol_general;
    private javax.swing.JButton bt_agregar_empleado;
    private javax.swing.JButton bt_agregar_jefe;
    private javax.swing.JButton bt_color_cliente;
    private javax.swing.JButton bt_color_empleado;
    private javax.swing.JButton bt_color_familiar;
    private javax.swing.JButton bt_color_jefe;
    private javax.swing.JComboBox<String> cb_baleadas;
    private javax.swing.JComboBox<String> cb_empleados;
    private javax.swing.JTextField cliente_jefe;
    private javax.swing.JTextField dinero_cliente;
    private javax.swing.JSpinner edad_cliente;
    private javax.swing.JSpinner edad_empleado;
    private javax.swing.JSpinner edad_familiar;
    private javax.swing.JSpinner edad_jefe;
    private javax.swing.JDialog eliminar;
    private javax.swing.JMenuItem eliminar_tabla;
    private javax.swing.JTextField entrada_empleado;
    private javax.swing.JComboBox<String> estado_empleado;
    private javax.swing.JTextField ganancias_jefe;
    private javax.swing.JMenuItem guardar_baleadas;
    private javax.swing.JMenuItem guardar_cliente;
    private javax.swing.JMenuItem guardar_empleado;
    private javax.swing.JMenuItem guardar_familiares;
    private javax.swing.JMenuItem guardar_gatos;
    private javax.swing.JMenuItem guardar_jefes;
    private javax.swing.JMenuItem guardar_ordenes;
    private javax.swing.JTextField id_cliente;
    private javax.swing.JTextField id_empleado;
    private javax.swing.JTextField id_familiar;
    private javax.swing.JTextField id_jefe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JTree jTree2;
    private javax.swing.JTextField lugar_cliente;
    private javax.swing.JTextField lugar_empleado;
    private javax.swing.JTextField lugar_familiar;
    private javax.swing.JTextField lugar_jefe;
    private javax.swing.JPopupMenu menu_popup;
    private javax.swing.JPopupMenu menu_popup2;
    private javax.swing.JComboBox<String> nacionalidad_cliente;
    private javax.swing.JComboBox<String> nacionalidad_empleado;
    private javax.swing.JComboBox<String> nacionalidad_familiar;
    private javax.swing.JComboBox<String> nacionalidad_jefe;
    private javax.swing.JTextField nombre_cliente;
    private javax.swing.JTextField nombre_empleado;
    private javax.swing.JTextField nombre_familiar;
    private javax.swing.JTextField nombre_jefe;
    private javax.swing.JDialog ordenes;
    private javax.swing.JTextField peso_gato;
    private javax.swing.JTextField precio_baleadas;
    private javax.swing.JTextField precio_gato;
    private javax.swing.JTextField salida_empleado;
    private javax.swing.JComboBox<String> seccion_empleado;
    private javax.swing.JComboBox<String> seccion_jefe;
    private javax.swing.JTextField sueldo_empleado;
    private javax.swing.JTable tabla_general;
    private javax.swing.JTextField ticket_cliente;
    // End of variables declaration//GEN-END:variables
    int edad;
    int id;
    double peso;
    double altura;
    double precio;
    String nacionalidad;
    String lugar_nacimiento;
    String nombre;
    Color color_piel;
    String seccion_trabajo;
    String hora_entrado;
    String hora_salida;
    double sueldo;
    String estado;
    int ticket;
    double dinero;
    int clientes_atendidos;
    double ganacias;
    ArrayList lista = new ArrayList();
    DefaultMutableTreeNode nodo_selecionado;
    Persona persona_seleccionado;
    Familiares familiar_seleccionado;
}
